[workspace]
members = [ "rt","macroe", "playground", "ffi"]
resolver = "2"

[workspace.dependencies]
syn = { version = "2", features = ["full", "extra-traits"] }
quote = { version = "1.0" }
proc-macro2 = "1.0.43"

[profile.dev]
codegen-units = 1
