[package]
name = "playground"
version = "0.1.0"
edition = "2021"
description = "A playground for macro use to test macro in macroe"

[dependencies]
macroe ={ path = "../macroe"}
rt = { path = "../rt"}
ctor = { workspace = true }
playground_dep = { path = "../playground_dep" }

