[package]
name = "playground"
version = "0.1.0"
edition = "2021"
description = "A playground for macro use to test macro in macroe"

[dependencies]
macroe ={ path = "../macroe"}
knowledge_ai = { path = "../knowledge_ai"}