name: Rust

on:
  push:
    branches: [ "default" ]
  pull_request:
    branches: [ "default" ]
  schedule:
    # UTC 周一20点 = 北京时间周二4点
    - cron: '0 20 * * 1'  

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
