name: Template CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    # UTC 周一20点 = 北京时间周二4点
    - cron: '0 20 * * 1'  

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    
    - name: Cache cargo
      uses: actions/cache@v3
      with:
        path: ~/.cargo
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Install and test template
      run: |
        cargo install cargo-generate
        mkdir /tmp/test && cd /tmp/test
        cargo generate --path ${{ github.workspace }} --name test \
          --define playground=app --define macroe=macros
        cd test && cargo build && cargo test

